set identity_insert lojamix.dbo.consignacao_venda on
insert into lojamix.dbo.consignacao_venda(id_consignacao_venda,id_entidade_cliente,id_filial,id_local_estoque,situacao,codigo_consignacao,data_hora_cadastro,id_usuario_cadastro,data_hora_alteracao,id_usuario_alteracao,data_hora_cancelamento,id_usuario_cancelamento,data_previsao_devolucao,data_hora_finalizacao,id_usuario_vendedor,id_documento_estoque,observacao,id_pedido_venda)
select consi.id_consignacao,id_entidade,id_filial,1,situacao,consi.id_consignacao,data_hora_cadastro,
id_usuario_cadastro,data_hora_alteracao,id_usuario_alteracao,null, null, CURRENT_TIMESTAMP,null,null,null,observacao,pedido.id_pedido_venda from hiper.dbo.consignacao as consi
left join hiper.dbo.consignacao_pedido_venda as pedido ON pedido.id_consignacao = consi.id_consignacao
set identity_insert lojamix.dbo.consignacao_venda off