insert into lojamix.dbo.item_pedido_venda
Select id_pedido_venda,sequencia_item, id_produto, valor_unitario,observacao,valor_unitario_com_desconto,cancelado,
hash_md5,3,'','',valor_unitario,0.000000,NULL
from hiper.dbo.item_pedido_venda where id_pedido_venda <> 1

SET IDENTITY_INSERT LOJAMIX.DBO.PEDIDO_VENDA ON
insert into lojamix.dbo.pedido_venda
(
id_pedido_venda,id_entidade_cliente,tipo_frete,valor_frete,id_entidade_transportadora,codigo_pedido_cliente,id_representante,data_previsao_entrega_inicial,
data_previsao_entrega_final,data_previsao_faturamento,observacao,situacao,id_usuario_geracao,data_hora_geracao,id_usuario_englobamento,data_hora_englobamento,
id_englobamento,operacao,nome_cliente_orcamento,nome_contato_cliente_orcamento,cpf_cliente_orcamento,cnpj_cliente_orcamento,ie_cliente_orcamento,
logradouro_cliente_orcamento,numero_endereco_cliente_orcamento,bairro_cliente_orcamento,complemento_cliente_orcamento,cep_cliente_orcamento,
id_cidade_cliente_orcamento,fone_ddd_cliente_orcamento,fone_numero_cliente_orcamento,celular_ddd_cliente_orcamento,celular_numero_cliente_orcamento,
email_cliente_orcamento,id_usuario_vendedor,data_validade_orcamento,id_filial_venda,nsu,id_tabela_preco,hash_md5,situacao_impressao,exportado_modamix,
id_documento_estoque,codigo_loja_virtual,id_local_estoque,codigo_integracao_umovme,origem_pedido_venda,cliente_consumidor_final,percentual_desconto_geral,
valor_desconto_geral,tipo_desconto,id_loja_virtual,situacao_entrega,controlar_entrega_itens
)
select 
id_pedido_venda, id_entidade_cliente,1,valor_frete,id_entidade_transportadora,
codigo_pedido_cliente,id_representante, data_previsao_entrega_inicial,
data_previsao_entrega_final, data_previsao_faturamento,observacao, 
situacao,id_usuario_geracao,data_hora_geracao, id_usuario_englobamento,
data_hora_englobamento,id_englobamento,operacao,nome_cliente_orcamento, 
nome_contato_cliente_orcamento, cpf_cliente_orcamento, cnpj_cliente_orcamento,
ie_cliente_orcamento,logradouro_cliente_orcamento,numero_endereco_cliente_orcamento,
bairro_cliente_orcamento,complemento_cliente_orcamento,cep_cliente_orcamento,id_cidade_cliente_orcamento,
fone_ddd_cliente_orcamento, fone_numero_cliente_orcamento, 
celular_ddd_cliente_orcamento,celular_numero_cliente_orcamento,email_cliente_orcamento,id_usuario_vendedor,
data_validade_orcamento, id_filial_venda,id_pedido_venda,id_tabela_preco,hash_md5,
situacao_impressao,NULL,NULL,0,1,NULL,1,1,NULL,NULL,NULL,NULL,2,0 from hiper.dbo.pedido_venda
where id_pedido_venda <> 1
SET IDENTITY_INSERT LOJAMIX.DBO.PEDIDO_VENDA OFF
